"use client";
import { useState } from "react";
import { Sparkles, FileDown } from "lucide-react";
type Result = { job_id: string; preview_png: string; pdf_url: string; mode: string };
export default function Page() {
  const [text,setText]=useState("商売繁盛"); const [style,setStyle]=useState("edo-yose"); const [size,setSize]=useState(1024);
  const [seed,setSeed]=useState(1234); const [useAi,setUseAi]=useState(false); const [result,setResult]=useState<Result|null>(null); const [loading,setLoading]=useState(false); const [error,setError]=useState("");
  async function generate(){ setLoading(true); setError(""); setResult(null); try{ const r=await fetch("/api/generate",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({text,style,size,seed,use_ai:useAi})}); const d=await r.json(); if(!r.ok) throw new Error(d.error||"生成に失敗しました"); setResult(d);}catch(e:any){setError(e.message)}finally{setLoading(false)} }
  return <main className="container"><section className="hero"><div className="card"><h1>江戸文字<br/>生成システム</h1><p className="lead">入力文字を江戸文字風フォントで下書きし、ControlNet/LoRAまたはOpenCV補正で仕上げ、PDFとして出力します。</p><div className="steps"><div className="step">1. 入力文字</div><div className="step">2. 下書き生成</div><div className="step">3. ControlNet</div><div className="step">4. OpenCV補正</div><div className="step">5. PDF出力</div></div></div><div className="card"><div className="form"><label>出力したい文字</label><textarea value={text} onChange={e=>setText(e.target.value)} /><div className="row"><div><label>スタイル</label><select value={style} onChange={e=>setStyle(e.target.value)}><option value="edo-yose">江戸寄席文字</option><option value="kakuji">勘亭流寄り</option><option value="bold-sign">看板太字</option></select></div><div><label>画像サイズ</label><input type="number" value={size} min={512} max={1536} step={128} onChange={e=>setSize(Number(e.target.value))}/></div></div><div className="row"><div><label>Seed</label><input type="number" value={seed} onChange={e=>setSeed(Number(e.target.value))}/></div><div><label>AI生成</label><select value={useAi?"true":"false"} onChange={e=>setUseAi(e.target.value==="true")}><option value="false">OFF: OpenCV仕上げ</option><option value="true">ON: ControlNet+LoRA</option></select></div></div><button className="button" disabled={loading||!text.trim()} onClick={generate}><Sparkles size={18}/> {loading?"生成中...":"生成する"}</button>{error && <div className="error">{error}</div>}</div></div></section>{result && <section className="card" style={{marginTop:24}}><h2>生成結果</h2><div className="preview"><img src={result.preview_png} alt="生成プレビュー"/></div><p className="lead">生成モード: {result.mode}</p><div className="links"><a className="link" href={result.pdf_url} target="_blank"><FileDown size={16}/> PDFを開く</a><a className="link" href={result.preview_png} target="_blank">PNGを開く</a></div></section>}</main>
}
